### ISSUE TITLE
HPE Heaven OnDemand

### ISSUE THREAD

**Issue by ar-anvd** [Teamlyzer-PT/technical-issues#143]
Sentiment analysis API down.

**Comment by ghost** [comment]
Probably we need some alternative to replace it.

**Comment by ghost** [comment]
https://westeurope.dev.cognitive.microsoft.com/docs/services/TextAnalytics.V2.0/operations/56f30ceeeda5650db055a3c9/console
https://azure.microsoft.com/pt-br/services/cognitive-services/text-analytics/

**Comment by ghost** [comment]
This won't be fixed for now.
