### ISSUE TITLE
Update moderation area

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#209]
- [x] Update moderation area
- [x] Create area for revisions (only a company member can edit)
- [x] Create messages   

Notes:
- New area only for the admin. You click in the Offical Companies button, then open the list of revisions (each company can only have one revision) pending for validation. The admin can only approve / reject.

**Comment by teamlyzer** [comment]
![lkk](https://user-images.githubusercontent.com/30689205/59940355-612bcb80-9452-11e9-8431-0a3d649aba88.png)
![lkk1](https://user-images.githubusercontent.com/30689205/59940356-612bcb80-9452-11e9-8e06-47f6408055e0.png)
