### ISSUE TITLE
Create a new landing page for companies

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#212]
- [x] Create endpoint  /b2b/pricing
- [x] Include link to landing page about companies
- [x] Add contact form
- [x] Send emails
- [x] Layout / Design
- [x] FAQ
- [x] SEO
- [x] Copywriting

-------- 

- [x] Pricing page

**Comment by ghost** [comment]
Instructions to access employer account

Step1:Signup for employer account on ambitionbox.com from your work email id.

Step2:We will send a verification email to your inbox. Click the link in this email. It’s important that you do this.

Step3:One of our executives will give you a verification call on the number provided by you.

Step4: If we approve your request you will receive a set password email. Click the link in this email to set your employer account password.

Step5:You can now login to employer dashboard. Start editing your company page, respond to reviews, and do much more here.

**Comment by teamlyzer** [comment]
- Name
- Company name
- Work Email Address
- agree terms
