### ISSUE TITLE
Invite users to administer a company

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#214]
- [x] Create area to invite 
- [x] Create form (only email of the new user). Create validations
- [x] Create a table of logs for invites (`user_id | company_id | email | token | used | ts`)
- [x] Create new relation about users - company_team (*-1). This relation must have a field to check as active | inactive, who made the change and the date. The first is always made by the admin
- [x] Add users to tables
- [x] Create email templates
- [x] List of team members with option to soft-delete

Notes: 
- If the user has an account in TL then he only needs to click that link and he will be added to the company team. 
- ~If he is a new member, then he needs to click, and after receiving a new email with a temporary pass, replace it in the first login.~
- The first invite for a company is always made by admin. 
- Only admin, or if there is an user in the team, with the status activated, can invite new users for that team. 
- Obviously he can't invite for other teams where he doesn't belong.
- The email expire after click.

**Comment by teamlyzer** [comment]
![invite](https://user-images.githubusercontent.com/30689205/59944184-0a2af400-945c-11e9-9268-c0c110a96d43.png)

**Comment by ghost** [comment]
![xxxx](https://user-images.githubusercontent.com/30689205/59944714-63dfee00-945d-11e9-92ef-56bf7f26fb62.png)
![asd](https://user-images.githubusercontent.com/30689205/59944715-63dfee00-945d-11e9-86e0-9ca268d955aa.png)
![upload](https://user-images.githubusercontent.com/30689205/59944717-63dfee00-945d-11e9-970c-8e34d9bef75c.png)
![employ](https://user-images.githubusercontent.com/30689205/59944718-63dfee00-945d-11e9-8d01-0f84f585b287.png)
![Screenshot (1)](https://user-images.githubusercontent.com/30689205/59944719-64788480-945d-11e9-9bd5-d0ffe44716b0.png)

**Comment by ghost** [comment]
![col](https://user-images.githubusercontent.com/30689205/59957503-d5855f80-9490-11e9-9116-69a404bae0a9.png)
