### ISSUE TITLE
Interview duration

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#251]
Maybe confusing when the process has multiple interviews

**Comment by ghost** [comment]
@GFSS7  not sure how to handle this. Maybe agg the hours of all interviews during the same process. If so, is just change the label and probably increase the dropdown of hours from 8 to 16 or something like that

**Comment by GFSS7** [comment]
não é muito fácil de resolver, o pessoal junta o tempo dos challenge + interviews, podiamos separar isto:
Tempo despendido em entrevistas presenciais / skypes = xxx
Tempo a resolver provas técnicas = xxx

Acho que também não temos o tempo em que demora o processo, podia ser algo como:
(tempo desde da candidatura ou primeiro contacto até ao final do processo) 

1 semana
2 semanas
3 semanas
mais de 1 mês
mais de 2 meses 
mais de 3 meses

**Comment by ghost** [comment]
@GFSS7 por agora que dizes a na label mudar-mos para "Duração total das entrevistas + challenges" ou algo melhor que dê a enteder que engloba tudo?

Essas alterações maiores não consigo fazê-las por agora.

![Screenshot (47)](https://user-images.githubusercontent.com/30689205/73280076-ebf15780-41e5-11ea-9d45-606ca8df85b4.png)
