### ISSUE TITLE
Company page bugs

### ISSUE THREAD

**Issue by fabiulous** [Teamlyzer-PT/technical-issues#286]
- [x] Email a ser dado para empresa não e obvio.
Leva a crer que deve ser o email da empresa, mas deve ser o email para login e conta de utilizador

- [x] Apos registo, o botão seleccionar todos nao funciona https://github.com/teamlyzer/technical-issues/issues/284

- [x] Convidar utilizadores deve ser por contas criadas, porque a conta de um utilizador nem sempre vai ter o email profissional da empresa

- https://pt.teamlyzer.com/companies/quero-emprego/addresses

- [x] Internal server error ao tentar adicionar uma morada:
39.602879, -9.070010
Nazaré
Leiria

**Comment by ghost** [comment]
@shizpi no 1 e 3 vamos manter, para conseguirmos fazer a validação mínima de a pessoa trabalhar na empresa. Se já tiver uma conta pessoal tem criar outra profissional.

No 1 vai criar atrito ao registo ter a explicação. Não se deve é enviar convites a menos que a pessoa tenha a conta que fornece registada. No demo deveria ter verificado antes de enviar o convite.

**Comment by ghost** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/30689205/65461345-9679f800-de4b-11e9-9b53-31d1863c2ac8.png)

Mockup de demo
