### ISSUE TITLE
Company page bugs

### ISSUE THREAD

**Issue by fabiulous** [Teamlyzer-PT/technical-issues#295]
- Wrong company logo after edit:
<img width="537" alt="Screenshot 2019-09-24 at 19 42 37" src="https://user-images.githubusercontent.com/10537219/65536502-d43a5780-df03-11e9-9095-3df9cb9dba17.png">

https://pt.teamlyzer.com/static/uploads/companies/140x108_temp/quero-emprego.png?31

- Buttons too big in company edit page
<img width="505" alt="Screenshot 2019-09-24 at 19 43 46" src="https://user-images.githubusercontent.com/10537219/65536491-cedd0d00-df03-11e9-96b9-0f5e024b0247.png">

- Possible to add location in wrong district
<img width="443" alt="Screenshot 2019-09-24 at 19 46 25" src="https://user-images.githubusercontent.com/10537219/65536593-09df4080-df04-11e9-8d5b-7f3bd8bf5684.png">

- Delete button is almost not visible
<img width="239" alt="Screenshot 2019-09-24 at 19 50 08" src="https://user-images.githubusercontent.com/10537219/65536902-8d009680-df04-11e9-8a89-4cf1e228c41c.png">

**Comment by ghost** [comment]
-1 is now solved
-2  is now solved ("Cancelar alterações de rascunho" to "Cancelar rascunho")
-3 TODO (not sure how to handle this) btw we are using Geocoder() from [google](https://developers.google.com/maps/documentation/javascript/reference/geocoder) @shizpi
-4 the opacity was intentional

**Comment by ghost** [comment]
-3 I think we can ignore this for now
