### ISSUE TITLE
Engineering interview process

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#306]
- [x] Define requirements
- [x] Layout
- [x] Front-end implementation
- [x] Create model
- [x] Migrate
- [x] Update side menu
- [x] Create Back-end in company page

**Comment by ghost** [comment]
Inspiration: https://github.com/goodNotes/interviews

**Comment by ghost** [comment]
![1](https://user-images.githubusercontent.com/30689205/66745043-e14cc580-ee75-11e9-92be-d07ef151f53f.png)
![2](https://user-images.githubusercontent.com/30689205/66745045-e1e55c00-ee75-11e9-99ae-1dc10c22ad89.png)
![3](https://user-images.githubusercontent.com/30689205/66745046-e1e55c00-ee75-11e9-9a18-96b41166a072.png)
![4](https://user-images.githubusercontent.com/30689205/66745047-e1e55c00-ee75-11e9-9364-ae3ce692f010.png)
![5](https://user-images.githubusercontent.com/30689205/66745048-e1e55c00-ee75-11e9-976e-94e59752a7fe.png)
![6](https://user-images.githubusercontent.com/30689205/66745050-e27df280-ee75-11e9-92fc-4c3fde231616.png)
![7](https://user-images.githubusercontent.com/30689205/66745051-e27df280-ee75-11e9-89d1-8a05462ff5f8.png)
![8](https://user-images.githubusercontent.com/30689205/66745052-e27df280-ee75-11e9-9ebd-da1c460b58cf.png)
![9](https://user-images.githubusercontent.com/30689205/66745053-e27df280-ee75-11e9-9a01-e2990f1f28d0.png)
![10](https://user-images.githubusercontent.com/30689205/66745054-e27df280-ee75-11e9-8d62-e1dab572831e.png)
![11](https://user-images.githubusercontent.com/30689205/66745055-e3168900-ee75-11e9-843f-649f4118856a.png)
![12](https://user-images.githubusercontent.com/30689205/66745056-e3168900-ee75-11e9-8d05-2e6b3310f2a4.png)
![13](https://user-images.githubusercontent.com/30689205/66745057-e3168900-ee75-11e9-9421-bda99dc3f6cf.png)
![14](https://user-images.githubusercontent.com/30689205/66745058-e3168900-ee75-11e9-95c0-01872e88b4ef.png)
![15](https://user-images.githubusercontent.com/30689205/66745059-e3af1f80-ee75-11e9-8a00-71495cde4ec7.png)

**Comment by ghost** [comment]
https://auth0.com/blog/how-we-hire-engineers/

**Comment by teamlyzer** [comment]
We will use markdown only for lists.
