### ISSUE TITLE
Create list of team values

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#313]
- Interage com a comunidade
- A equipa é diversificada
- Feedback contínuo
- Membros impressionantes na equipa
- Colaboração entre departamentos
- Comunicação aberta
- Organização horizontal
- Usa muitos chapéus
- Fortemente orientado para a equipa

**Comment by fabiulous** [comment]
- hierarquia plana
- foco no cliente
- foco no produto
- foco nos resultados

**Comment by ghost** [comment]
E preciso criar uma lista final de valores para selecionar

**Comment by GFSS7** [comment]
Aberta à comunidade
A equipa é diversificada
Feedback contínuo e 360º 
Membros impressionantes na equipa
Colaboração entre departamentos
Comunicação aberta e transparente
Organização horizontal
Organização hierárquica 
Orientada ao produto 
Foco nos resultados 
Foco no cliente 
Foco em métricas e KPIs
