### ISSUE TITLE
Create list of engineering practices

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#314]
- Código de alta qualidade
- Pair programming 
- Contribuidor de código aberto
- Usa metodologias ágeis
- Tecnologias de ponta
- Ambiente acelerado
- Entrega contínua

**Comment by fabiulous** [comment]
- Escrever código no primeiro dia
- One command setup
- Unit testing
- Integration testing

**Comment by GFSS7** [comment]
Sugestão:

Pair programming 
Aberta a OpenSource
Usa metodologias ágeis
Tecnologias de ponta / recentes
Ambiente de Start-up     
CI/CD
Bom onboarding técnico (Escrever código no primeiro dia , boa documentação etc)
One command setup 
Código de alta qualidade ou Focada em Qualidade (Unit testing, Integration testing, planos de QA, boas praticas de SW; etc)

eventualmente podemos tirar tudo o que está entre ( ) e controlar um botão "?" e depois ai explicar
