### ISSUE TITLE
Create list of benefits

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#315]
- Comida grátis
- Dias de hackers internos
- Orçamento de treinamento
- Bebidas gratuitas (chá, café, água, ...)
- Estacionamento grátis
- Chuveiro
- Mesa de bilhar
- Máquina de gelado
- Máquina de cerveja
- Formação interna
- Orçamento para conferências
- Eventos de teambuilding
- Seguro de saúde privado
- Smartphone para uso privado
- Portátil para uso privado
- Carro para uso privado
- Dias adicionais de férias
- Cozinha
- Cantina
- Estacionamento para bicicletas
- Jardim da infância
- Ginásio
- Sala de jogos
- Fruta
- Trabalho remoto
- Horário de trabalho flexível
- Auxilio creche
- Seguro de vida
- Fácil acesso ao transporte público
- Stock options
- Bónus para eventos pessoais (casamento, nascimento de filho, aniversário)
- Programa de referenciação
- Bónus anual
- Subsidio para actividades fisicas
- Oportunidades internacionais

**Comment by teamlyzer** [comment]
- Free snacks
- In-house hack days
- Training budget
- Free beverages
- Free parking
- Shower
- Pool Table
- Ice-Cream Machine
- In-house trainings
- Conference budget
- Team Events
- Private health care
- Sport subscription
- Mobile phone
- Kitchen
- Canteen
- Free coffee
- Bike parking
- Kindergarten
- Gym
- Play room

**Comment by ghost** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/30689205/68205398-1e622e80-ffc2-11e9-8ab7-831dbe44fc74.png)

**Comment by ghost** [comment]
Benefícios
ACESSOS
— Estação de autocarros
— Estação de comboios
— Estação de metro
— Parque automóvel gratuito
— Parque de bicicletas gratuito
— Parque de motos gratuito
— Transporte para colaboradores
ATIVIDADES
— Atividades de responsabilidade social
— Eventos team building
— Grupos (desporto, cozinha…)
— Sala de jogos
— Viagem anual de empresa
BÓNUS
— Plano de Pensões
— Prémios regulares
— Revisão regular de salário
— Stock options
CULTURA
— Espírito de start-up
— Estrutura flat
— Sem dress code
EQUIPAMENTOS
— Escolha de hardware
— Escolha de sistema operativo
— Tecnologias de ponta
— Telemóvel da empresa
— Viatura da empresa
FACILITIES
— Área de serviços e shopping
— Área verde
— Centro de cidade
— Creche próxima
FÉRIAS
— Dias extra de férias
— Folga de aniversário
FORMAÇÃO
— Formação em línguas
— Formação técnica
GINÁSTICA E RELAXAMENTO
— Aulas de fitness e ginástica
— Espaços de relaxamento
— Ginásio na empresa
— Ginásio próximo
HORÁRIO TRABALHO
— Horário fixo
— Horário flexível
— Trabalho em casa
— Trabalho nómada
OUTROS
— Agile methodology
— Alojamento primeiros meses
— Descontos em serviços
— Mobilidade internacional
— Ticket educação
— Ticket infância
REFEIÇÕES
— Cantina na empresa
— Copa para refeições
— Fruta, snacks e bebidas
— Sala de refeições
— Subsídio de alimentação
SEGUROS
— Seguro de saúde para família
— Seguro de saúde para trabalhador
— Seguro de vida

**Comment by ghost** [comment]
Stackoverflow tem montes de beneficios, ver o q da pra usar

https://stackoverflow.com/jobs/companies/www-freiheit-com

**Comment by ghost** [comment]
https://github.com/teamlyzer/technical-issues/issues/18

**Comment by ghost** [comment]
https://docs.google.com/spreadsheets/d/1FBMTdz2J-_wnAVX9sJHn08m4lqvX8Qe41-VD4KwTBro/edit#gid=0

**Comment by GFSS7** [comment]
Lista mais resumida:

> Bons acessos (Perto de transportes públicos)
> Estacionamento Gratuito (ou com condições especiais 
> Atividades de responsabilidade social
> Promove team buildings, viagens e actividades extra-trabalho 
> Actividades no escritório (snooker, ping pong, jogos etc) 
> Prémios de Performance
> Revisão regular de salario 
> Stock options 
> Cultura informal (sem dress code, hierarquia flat, etc)
> Telemóvel da empresa para uso pessoal
> Viatura da Empresa 
> Escolha do Hardware
> Escolha do sistema operativo 
> Mais de 22 dias de férias 
> Dias extra (aniversário, carnaval, Natal) 
> Formação / Conferencias internacionais
> Certificações 
> Ginásio 
> Flexibilidade de horario 
> Possibilidade de homeoffice
> 100% Remota 
> Descontos e parcerias relevantes 
> Tickets educação/infância
> Mobilidade internacional 
> Cantina
> Copa para refeições
> Comida,  fruta e bebidas 
> Seguro de saude 
> Seguro de saude gratuito para a familia
