### ISSUE TITLE
Number of team members by department

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#316]
![100](https://user-images.githubusercontent.com/30689205/66745223-57e9c300-ee76-11e9-8768-4eecdd49358b.png)
![101](https://user-images.githubusercontent.com/30689205/66745224-57e9c300-ee76-11e9-8047-cf0684dbcddd.png)

**Comment by ghost** [comment]
Free text or some more complicated approach, per departments, .. in this case we need to validate duplicated stuff.

**Comment by teamlyzer** [comment]
@GFSS7 achas que vale a pena ter isto? E provavel que fique desactualizado rapidamente
