### ISSUE TITLE
Vacation policy

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#317]
![300](https://user-images.githubusercontent.com/30689205/66745353-9ed7b880-ee76-11e9-83f0-58e3fd55617b.png)
![301](https://user-images.githubusercontent.com/30689205/66745354-9f704f00-ee76-11e9-862d-a0479d827a93.png)
![303](https://user-images.githubusercontent.com/30689205/66745605-566cca80-ee77-11e9-9916-7da575a94318.png)

**Comment by ghost** [comment]
Nothing to see here. Free text field

**Comment by fabiulous** [comment]
Flexile work hours should be it's own boolean.
A lot of people are looking for jobs with flexible schedule, so this could be a nice to have
