### ISSUE TITLE
Tech stack

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#318]
![400](https://user-images.githubusercontent.com/30689205/66745633-700e1200-ee77-11e9-9b98-24e1c3e09f71.png)
![401](https://user-images.githubusercontent.com/30689205/66745634-700e1200-ee77-11e9-94f4-3bf6b4a077e1.png)
![402](https://user-images.githubusercontent.com/30689205/66745635-700e1200-ee77-11e9-8038-ae294ee97b0f.png)
![403](https://user-images.githubusercontent.com/30689205/66745636-700e1200-ee77-11e9-8fad-80fc95620e8c.png)
![404](https://user-images.githubusercontent.com/30689205/66745637-70a6a880-ee77-11e9-8d29-7c94c6e19754.png)
![405](https://user-images.githubusercontent.com/30689205/66745638-70a6a880-ee77-11e9-9bc7-e26aec24d443.png)
![406](https://user-images.githubusercontent.com/30689205/66745640-70a6a880-ee77-11e9-84d4-65730f55f61d.png)
![407](https://user-images.githubusercontent.com/30689205/66745641-70a6a880-ee77-11e9-8d35-c1ad1a932a1b.png)
![408](https://user-images.githubusercontent.com/30689205/66745642-713f3f00-ee77-11e9-8bdb-b88c1f9ca21f.png)

**Comment by ghost** [comment]
We have two options. Or we use tags or free text.

**Comment by fabiulous** [comment]
Let's use tags. We have a bunch of them in Quero's DB, but they need cleaning

**Comment by ghost** [comment]
https://github.com/teamlyzer/technical-issues/issues/252
