### ISSUE TITLE
Create new salary 

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#33]
We need to develop a new way to allow users to inser salary
- [x] Create layout
- [x] Define fields/models 
- [x] Define validators - account limit per day / ip / etc
- [x] Total number of reviews needs to be updated in landing page, industry and company page 
- [x] Implementation of python function (check user history to avoid duplicated salaries for the same company since job review allows to post salary info too)
- [x] Testing

https://github.com/teamlyzer/technical-issues/issues/34

**Comment by teamlyzer** [comment]
`update companies_company set most_reviewed_salary = 0;` in prod
