### ISSUE TITLE
Update schema

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#334]
“sameAs”- this property is the key.

These links provide 1) third party confirmation2) credibility3) context4) additional information

Typical examples of great sameAs links:

Wikipedia
Wikidata
Crunchbase
Official company listing (for example Companieshouse.gov.uk)
Business organizations of which the company is a member
Your company profile pages on review sites

https://www.semrush.com/blog/schema-markup-for-company-corporations/

**Comment by ghost** [comment]
localbusiness not working as expected

**Comment by teamlyzer** [comment]
Temos de procurar para as empresas maiores com mais reviews as paginas de face, linked, etc. O melhor possivel. O talent portugal ja tem isso, podemos copiar.

Isto e importante para o google entender

**Comment by ghost** [comment]
We don't have time for this now.
