### ISSUE TITLE
Change images of industries

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#336]
- https://pt.teamlyzer.com/companies/industries

Subpage:
- https://pt.teamlyzer.com/companies/industries/bancos-servicos-financeiros
...

**Comment by teamlyzer** [comment]
E importante alguem pegar nisto

**Comment by GFSS7** [comment]
As que estão  servem enquanto não tiveremos budget - acho que isto seria algo mais a longo prazo. Quando tivermos $$$ ou pagamos a um designer ou a um banco de imagens como deve de ser

**Comment by ghost** [comment]
Missing h1
