### ISSUE TITLE
Improve label of AC

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#354]
![68602620-9935b880-049e-11ea-81dc-6ff7a7856ef7](https://user-images.githubusercontent.com/30689205/70434079-29a1f180-1a7b-11ea-9ea2-26ce588bd34d.png)

**Comment by GFSS7** [comment]
@teamlyzer podes especificar o que precisas aqui? especificar a % de ajudas de custo parece-me suficiente, pode é atrofiar a calculadora...

**Comment by ghost** [comment]
@GFSS7 

![Screenshot (43)](https://user-images.githubusercontent.com/30689205/73273633-3d94e480-41dc-11ea-9fcb-2a3b209d4516.png)

O problema é que a ideia é colocar o **valor bruto + ajudas de custo** no primeiro slide. No segundo slider deve colocar-se quanto desse valor são ajudas.

E o que está a acontecer às vezes é isto: https://github.com/teamlyzer/userfeedback/issues/11

A questão é melhorar as labels para isto ficar mais perceptivel. Alterações de código / logica não é fazível agora.
