### ISSUE TITLE
Create new explorer page of salaries

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#37]
- [x] Define requirements
- [x] Define UI
- [x] Define UX
- [x] SEO 
- [x] Python function
- [x] Testing

http://pygal.org/en/stable/

- area
- professions
- junior/senior
- tags
- ~~working time~~
- ~~salary-range~~
- ~~sentiment analysis (agg)~~
- ~~city~~

**Comment by teamlyzer** [comment]
#pagina de empresa -> salário detalhado por profissão

#grafico 1
- Histograma da distribuição
- AVG salário mensal / AVG salário anual

#grafico 2
- AVG salário mensal Senior
- AVG salário mensal Junior
- AVG salário mensal Senior global
- AVG salário mensal Senior Junior

#grafico 3
#TODO

#grafico 4 
#TODO

**Comment by ghost** [comment]
https://hired.com/salary-calculator

![Screenshot (11)](https://user-images.githubusercontent.com/30689205/54443660-f410e780-4738-11e9-9af8-d9dba27b7ffc.png)

**Comment by ghost** [comment]
glassdoor

![Screenshot (9)](https://user-images.githubusercontent.com/30689205/54222142-b750b080-44ec-11e9-9d7c-24e69497afab.png)

**Comment by ghost** [comment]
payscale

![Screenshot (10)](https://user-images.githubusercontent.com/30689205/54222398-4067e780-44ed-11e9-89c3-843b4168aea4.png)

**Comment by ghost** [comment]
paysa

![Screenshot (11)](https://user-images.githubusercontent.com/30689205/54222602-a6ed0580-44ed-11e9-9be4-a90cffd311c4.png)

**Comment by ghost** [comment]
hackajob

![Screenshot (14)](https://user-images.githubusercontent.com/30689205/54274334-bf0d6500-457f-11e9-8d20-ec6358567711.png)
![Screenshot (13)](https://user-images.githubusercontent.com/30689205/54274335-bfa5fb80-457f-11e9-8ce5-bd0c0800c30b.png)

**Comment by ghost** [comment]
https://stackoverflow.com/jobs/salary/results?l=Madrid%2c+Spain&ed=0&ex=2&ff=1&dr%5B0%5D=DatabaseAdministrator&tl%5B0%5D=javascript

![Screenshot (15)](https://user-images.githubusercontent.com/30689205/54443699-068b2100-4739-11e9-9c05-c409de1f7b2b.png)

**Comment by ghost** [comment]
https://triplebyte.com/software-engineer-salary

![Screenshot (25)](https://user-images.githubusercontent.com/30689205/55391706-cd70f000-5531-11e9-90ef-685d50885c8a.png)

**Comment by ghost** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/30689205/56032485-34548d00-5d1a-11e9-8b4f-d4826e5739f6.png)

**Comment by ghost** [comment]
http://pygal.org/en/stable/documentation/configuration/serie.html#fill
http://pygal.org/en/stable/documentation/configuration/serie.html#show-dots
http://pygal.org/en/stable/documentation/types/line.html#stacked
http://pygal.org/en/stable/documentation/configuration/interpolations.html#interpolate

**Comment by ghost** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/30689205/56897351-3a6e9b80-6a86-11e9-95ff-b63642d5ee3d.png)
