### ISSUE TITLE
Create metrics in company page

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#381]
- Pageviews
- Unique users

Check Yandex API

**Comment by teamlyzer** [comment]
Add pageviews

**Comment by ghost** [comment]
https://tech.yandex.com/metrika/doc/api2/api_v1/intro-docpage/

https://api-metrica.yandex.net/stat/v1/data?ids=38340835&metrics=ym:s:pageviews&date1=365daysAgo&pretty=true

https://api-metrika.yandex.net/stat/v1/data?metrics=ym:s:visits&filters=ym:s:pageViews>5&id=38340835&date1=365daysAgo&pretty=true

https://api-metrika.yandex.net/stat/v1/data/bytime?metrics=ym:s:pageviews&date1=30daysAgo&date2=today&group=day&id=44147844&pretty=true

ym:s:pageviews

&dimensions=ym:pv:URL=https://pt.teamlyzer.com/companies/vodafone


https://api-metrika.yandex.net/stat/v1/data?preset=tech_platforms&dimensions=ym:s:browser&id=44147844

https://api-metrica.yandex.net/stat/v1/data?dimensions=ym:s:searchEngineName&metrics=ym:s:visits,ym:s:users&filters=ym:pv:URL=='https://pt.teamlyzer.com/companies/vodafone'&id=38340835&pretty=true

https://api-metrica.yandex.net/stat/v1/data?dimensions=ym:s:searchEngineName&metrics=ym:s:pageviews&filters=ym:pv:URL=='https://pt.teamlyzer.com/companies/vodafone'&id=38340835&pretty=true&date1=365daysAgo

https://api-metrica.yandex.net/stat/v1/data?dimensions=ym:s:searchEngineName&metrics=ym:s:pageviews&filters=ym:pv:URL=='https://pt.teamlyzer.com/companies/vodafone'&id=38340835&pretty=true&date1=365daysAgo
