### ISSUE TITLE
Change click in rating to on mouse hover (rating details)

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#382]
When we see a job review,  we need to click in rating to see the details of that rating.

**Comment by ghost** [comment]
@shizpi check it out. Fica um bocado desequilibrada a pagina. Em produção ta a V2 mas acho que a V1 está mais equilibrada.

**Comment by ghost** [comment]
![v2](https://user-images.githubusercontent.com/30689205/81032995-e1e89000-8e89-11ea-8d55-edfe71cb4261.png)
![v1](https://user-images.githubusercontent.com/30689205/81032996-e3b25380-8e89-11ea-83cf-06b88e03a648.png)

**Comment by fabiulous** [comment]
second seems better
