### ISSUE TITLE
Flag to delete review

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#416]
@GFSS7 @shizpi 

É preciso decidir o que fazer aqui. Inicialmente era possível apagar reviews. Com a cena do blockchain deixou de fazer sentido. No entanto qualquer pessoa pode flagar reviews sempre. 

E o pior é que se **dois moderadores** disserem que é para apagar a review ela é mesmo apagada da nossa bd (mas mantida na blockchain como é óbvio). Deixa de haver consistência. Não pode acontecer.

Soluções
a) Remover as flags simplesmente (cortar o mal pela raiz, resolve tudo)
b) Remover a opção de flagar reviews depois de entrar na blockchain
c) Os moderadores da comunidade deixam de poder moderar flags
d) Os moderadores da comunidade deixam de poder moderar flags depois de entrar na blockchain

Voto na **b** e **d**

**Comment by GFSS7** [comment]
e se a flag obrigar a uma justificação e sermos nós juntamente com os moderadores a decidir se faz sentido apagar ou não?

**Comment by fabiulous** [comment]
**d**

Penso que mais tarde se pode "remover a review" na medida em que desaparece da lista e deixa de afetar o score da empresa, mas continua na blockchain e na nossa bd. Apenas acessivel numa pagina publica onde de para ver as reviews rejeitadas e removidas.
