### ISSUE TITLE
Covid19

### ISSUE THREAD

**Issue by fabiulous** [Teamlyzer-PT/technical-issues#428]
- a cena dos "despedimentos" acho que devia de estar ao pé do tipo de fonte
vais a ver e um "despedimento" pode ser um desabafo numa rede social e induz em erro

- bacano, concordo com o ...

**Comment by fabiulous** [comment]
![92812239_167241251144119_3860038261699248128_n](https://user-images.githubusercontent.com/10537219/79237724-c67ffb80-7e6e-11ea-81ca-d47164ded47f.png)

**Comment by ghost** [comment]
Acho que não vale a pena estar a mexer.
