### ISSUE TITLE
Create salary subpage for each role by company

### ISSUE THREAD

**Issue by ghost** [Teamlyzer-PT/technical-issues#96]
A more detailed page. Define what to include.

- gráfico de barras vertical de distribuição de salários
- mediana vs industria
- salário médio vs industria
- variação por senior/junior
- salario anual

**Comment by ghost** [comment]
De acordo, mas esse valor é uma extrapolação de um mês de trabalho "normal". Na prática para calcular o valor anual:

Pegando no mesmo exemplo. Ajudas de custo em 30% para 2200€ que correspondem a 660€.
- Salário total mensal de 2200€ * 11 meses = 24200€ (inclui AC)
- Salário base de 1540€ * 3 meses = 4620€ (sem AC no mês de férias, e subs de natal e férias)
- Salário total anual de 24200€ (11 meses) + 4620€ (3 meses) = 28820€

Acabaste de dar uma excelente ideia que é apresentar também este valor anual.

**Comment by teamlyzer** [comment]
#pagina de empresa -> salário detalhado por profissão

#grafico 1
- Histograma da distribuição
- AVG salário mensal / AVG salário anual

#grafico 2
- AVG salário mensal Senior
- AVG salário mensal Junior
- AVG salário mensal Senior global
- AVG salário mensal Senior Junior

#grafico 3
#TODO

#grafico 4 
#TODO
